### PR TITLE
Initial 1.8 port

### PR DESCRIPTION
**Pull request by marysaka**
Simple port for 1.8 (#27)

### CODE REVIEW

**Comment by boq** [comment]
Sorry, but having second copy of code is exactly what I'm trying to prevent from happening.

My current plans are to add some already planned functionality, and after that split to <=1.7.10 and >=1.8 branches, with new functionality already in.

**Comment by rubensworks** [comment]
Any news on this? Would love to see a 1.8 version of this mod.

**Comment by xbony2** [comment]
Judging from repo activity, I wouldn't get too hyped for it...

**Comment by boq** [comment]
Well, it's in plans. 

But I'm terrible at planning...
Maybe after I finish next release of other mods.

**Comment by jochuan** [comment]
any news on this ?

**Comment by xbony2** [comment]
Look at the commit history.

**Pull request closed without merging**
